[project]
name = "vertretungsplan-API"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "bs4>=0.0.2",
    "fastapi[standard]>=0.128.0",
    "regex>=2026.1.15",
    "requests>=2.32.5",
    "uvicorn>=0.40.0",
]
